graph TD
    COORD[Coordenador Geral]

    COORD --> PA[Ciclo Infinito]
    COORD --> PB[Loot & Lunch ]

    %% Ciclo Infinito
    PA --> PALP[Coordenador de Ciclo Infinito]

    PALP --> PAPL[Líder de Programação ]
    PAPL --> PAPROG[Programadores]

    PALP --> PADES[Líder Criativo ]
    PADES --> PAGD[Game Designer]
    PADES --> PALD[Level Designer]
    PADES --> PAUX[UX / Narrativa]

    PALP --> PAART[Líder de Arte ]
    PAART --> PAA2D[Artista 2D]
    PAART --> PAA3D[Artista 3D]
    PAART --> PAANIM[Animador]
    PAART --> PAUI[UI Artist]
    PAART --> PAAUD[Áudio]
    
    %% Loot & Lunch 
    PB --> PBLP[Coordenador de Loot & Lunch ]

    PBLP --> PBPL[Líder de Programação ]
    PBPL --> PBPROG[Programadores]

    PBLP --> PBDES[Líder Criativo ]
    PBDES --> PBGD[Game Designer]
    PBDES --> PBLD[Level Designer]
    PBDES --> PBUX[UX / Narrativa]

    PBLP --> PBART[Líder de Arte ]
    PBART --> PBA2D[Artista 2D]
    PBART --> PBA3D[Artista 3D]
    PBART --> PBANIM[Animador]
    PBART --> PBUI[UI Artist]
    PBART --> PBAUD[Áudio]
